######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 11 21:35:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network
CONFIG += console
LIBS += -L/usr/lib -lqjson

# Input
HEADERS += qdbox.h
SOURCES += qdbox.cpp
